--INSERT INTO movies(title, releaseYear, synopsis) VALUES('Harry Potter and the Philosopher''s Stone', 2001, 'Harry Potter has lived under the stairs at his aunt and uncle''s house his whole life. But on his 11th birthday, he learns he''s a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school''s kindly headmaster, Harry uncovers the truth about his parents'' deaths -- and about the villain who''s to blame."')

INSERT INTO movies(title, releaseYear, synopsis) VALUES('Star Wars',1977,'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.');

INSERT INTO movies(title, releaseYear, synopsis) VALUES('The Godfather',1972,'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.');

INSERT INTO movies(title, releaseYear, synopsis) VALUES('Avengers Endgame',2019,'After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos'' actions and restore balance to the universe.');

INSERT INTO movies(title, releaseYear, synopsis) VALUES('Parasite',2019,'A poor family, the Kims, con their way into becoming the servants of a rich family, the Parks. But their easy life gets complicated when their deception is threatened with exposure.');

INSERT INTO movies(title, releaseYear, synopsis) VALUES('Bloodshot',2020,'Ray Garrison, a slain soldier, is re-animated with superpowers.');